Repository brain-tec/l10n-switzerland, pull requests merged in 2019-04, with the labels that each got.

#232 Syncing from upstream OCA/l10n-switzerland (11.0)
  l10n_ch_mis_reports/data/mis_report_kpi.xml
Labels: 11.0

#233 Syncing from upstream OCA/l10n-switzerland (12.0)
  l10n_ch_mis_reports/data/mis.report.kpi.csv
  l10n_ch_states/README.rst
  l10n_ch_states/__manifest__.py
  l10n_ch_states/i18n/de.po
  l10n_ch_states/i18n/l10n_ch_states.pot
  l10n_ch_states/readme/CONTRIBUTORS.rst
  l10n_ch_states/readme/DESCRIPTION.rst
  l10n_ch_states/readme/USAGE.rst
  l10n_ch_states/static/description/index.html
  l10n_ch_zip/README.rst
  l10n_ch_zip/__init__.py
  l10n_ch_zip/__manifest__.py
  l10n_ch_zip/data/res.better.zip.csv
  l10n_ch_zip/data/res.city.csv
  l10n_ch_zip/data/res.city.zip.csv
  l10n_ch_zip/hooks.py
  l10n_ch_zip/i18n/de.po
  l10n_ch_zip/i18n/l10n_ch_zip.pot
  l10n_ch_zip/models/__init__.py
  l10n_ch_zip/models/city_zip.py
  l10n_ch_zip/readme/CONTRIBUTORS.rst
  l10n_ch_zip/readme/DESCRIPTION.rst
  l10n_ch_zip/readme/INSTALL.rst
  l10n_ch_zip/readme/USAGE.rst
  l10n_ch_zip/static/description/index.html
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/l10n_ch_states/odoo/addons/l10n_ch_states
  setup/l10n_ch_states/setup.py
  setup/l10n_ch_zip/odoo/addons/l10n_ch_zip
  setup/l10n_ch_zip/setup.py
Labels: 12.0

#234 Syncing from upstream OCA/l10n-switzerland (10.0)
  l10n_ch_pain_base/__manifest__.py
  l10n_ch_pain_base/models/account_payment_order.py
Labels: 10.0

#235 Syncing from upstream OCA/l10n-switzerland (8.0)
  l10n_ch_account_statement_base_import/static/description/icon.png
  l10n_ch_credit_control_payment_slip_report/static/description/icon.png
  l10n_ch_dta_base_transaction_id/static/description/icon.png
  l10n_ch_fds_postfinance/static/description/icon.png
  l10n_ch_fds_upload_dd/static/description/icon.png
  l10n_ch_fds_upload_sepa/static/description/icon.png
  l10n_ch_import_cresus/static/description/icon.png
  l10n_ch_lsv_dd/static/description/icon.png
  l10n_ch_payment_slip_base_transaction_id/static/description/icon.png
  l10n_ch_payment_slip_voucher/static/description/icon.png
  l10n_ch_scan_bvr/static/description/icon.png
  l10n_ch_sepa/static/description/icon.png
  l10n_ch_states/static/description/icon.png
Labels: 8.0

#236 Syncing from upstream OCA/l10n-switzerland (9.0)
  l10n_ch_bank_statement_import_postfinance/static/description/icon.png
  l10n_ch_fds_postfinance/static/description/icon.png
  l10n_ch_fds_upload_dd/static/description/icon.png
  l10n_ch_fds_upload_sepa/static/description/icon.png
  l10n_ch_lsv_dd/static/description/icon.png
  l10n_ch_pain_base/static/description/icon.png
  l10n_ch_pain_credit_transfer/static/description/icon.png
  l10n_ch_scan_bvr/static/description/icon.png
  l10n_ch_states/static/description/icon.png
Labels: 9.0

#237 Syncing from upstream OCA/l10n-switzerland (10.0)
  README.md
  l10n_ch_bank_statement_import_postfinance/static/description/icon.png
  l10n_ch_fds_postfinance/static/description/icon.png
  l10n_ch_fds_upload_dd/static/description/icon.png
  l10n_ch_fds_upload_sepa/static/description/icon.png
  l10n_ch_import_pain002/static/description/icon.png
  l10n_ch_lsv_dd/static/description/icon.png
  l10n_ch_pain_base/static/description/icon.png
  l10n_ch_pain_credit_transfer/static/description/icon.png
  l10n_ch_scan_bvr/static/description/icon.png
  l10n_ch_states/static/description/icon.png
Labels: 10.0

#238 Syncing from upstream OCA/l10n-switzerland (11.0)
  l10n_ch_account_tags/static/description/icon.png
  l10n_ch_mis_reports/static/description/icon.png
  l10n_ch_pain_base/static/description/icon.png
  l10n_ch_pain_credit_transfer/static/description/icon.png
  l10n_ch_states/static/description/icon.png
Labels: 11.0

#239 Syncing from upstream OCA/l10n-switzerland (12.0)
  l10n_ch_account_tags/static/description/icon.png
  l10n_ch_mis_reports/static/description/icon.png
  l10n_ch_states/static/description/icon.png
Labels: 12.0

#241 Syncing from upstream OCA/l10n-switzerland (10.0)
  README.md
  l10n_ch_lsv_dd/__manifest__.py
  l10n_ch_lsv_dd/i18n/l10n_ch_lsv_dd.pot
  l10n_ch_lsv_dd/views/banking_export_ch_dd_view.xml
Labels: 10.0

#240 [t114249] SEPA together with other Swiss payments
  l10n_ch_pain_base/models/account_payment_order.py
Labels: 11.0.project_pr_449

#244 fixing an obvious error from eeb26426f50e007e07ef4e1b423a3abe79da39f1
  l10n_ch_sepa/base_sepa/base_template/pain.001.001.03.xml.mako
Labels: 8.0

#246 Syncing from upstream OCA/l10n-switzerland (12.0)
  l10n_ch_base_bank/models/bank.py
  l10n_ch_base_bank/models/invoice.py
Labels: 12.0

#247 Syncing from upstream OCA/l10n-switzerland (11.0)
  l10n_ch_base_bank/i18n/de.po
  l10n_ch_base_bank/i18n/fr.po
  l10n_ch_base_bank/i18n/it.po
Labels: 11.0

#248 Syncing from upstream OCA/l10n-switzerland (12.0)
  l10n_ch_base_bank/i18n/fr.po
  l10n_ch_base_bank/i18n/it.po
  l10n_ch_base_bank/tests/test_bank.py
  l10n_ch_base_bank/tests/test_create_invoice.py
  l10n_ch_base_bank/tests/test_search_invoice.py
  l10n_ch_pain_base/README.rst
  l10n_ch_pain_base/__manifest__.py
  l10n_ch_pain_base/i18n/de.po
  l10n_ch_pain_base/i18n/l10n_ch_pain_base.pot
  l10n_ch_pain_base/migrations/11.0.1.0.0/post-migration.py
  l10n_ch_pain_base/models/account_move_line.py
  l10n_ch_pain_base/models/account_payment_line.py
  l10n_ch_pain_base/readme/CONTRIBUTORS.rst
  l10n_ch_pain_base/readme/DESCRIPTION.rst
  l10n_ch_pain_base/static/description/icon.png
  l10n_ch_pain_base/static/description/index.html
  l10n_ch_pain_credit_transfer/README.rst
  l10n_ch_pain_credit_transfer/__manifest__.py
  l10n_ch_pain_credit_transfer/i18n/de.po
  l10n_ch_pain_credit_transfer/i18n/l10n_ch_pain_credit_transfer.pot
  l10n_ch_pain_credit_transfer/readme/CONFIGURE.rst
  l10n_ch_pain_credit_transfer/readme/CONTRIBUTORS.rst
  l10n_ch_pain_credit_transfer/readme/DESCRIPTION.rst
  l10n_ch_pain_credit_transfer/readme/USAGE.rst
  l10n_ch_pain_credit_transfer/static/description/icon.png
  l10n_ch_pain_credit_transfer/static/description/index.html
  l10n_ch_pain_credit_transfer/tests/test_ch_sct.py
  l10n_ch_payment_slip/i18n/l10n_ch_payment_slip.pot
  l10n_ch_payment_slip/models/payment_slip.py
  l10n_ch_payment_slip/report/report.py
  l10n_ch_payment_slip/tests/test_payment_slip.py
  l10n_ch_payment_slip/wizard/isr_batch_print.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/l10n_ch_pain_base/odoo/addons/l10n_ch_pain_base
  setup/l10n_ch_pain_base/setup.py
  setup/l10n_ch_pain_credit_transfer/odoo/addons/l10n_ch_pain_credit_transfer
  setup/l10n_ch_pain_credit_transfer/setup.py
Labels: 12.0
