Repository brain-tec/l10n-switzerland, pull requests merged in 2019-07, with the labels that each got.

#254 [bt#5756] Bankverbindung eines Lieferanten lautet auf andere Adresse
  l10n_ch_sepa/base_sepa/base_template/pain.001.001.03.xml.mako
Labels: 7.0

#255 [bt#5756] Bankverbindung eines Lieferanten lautet auf andere Adresse
  l10n_ch_sepa/base_sepa/base_template/pain.001.001.03.xml.mako
Labels: 7.0

#256 [bt#5756] Bankverbindung eines Lieferanten lautet auf andere Adresse (#5756)
  l10n_ch_sepa/base_sepa/base_template/pain.001.001.03.xml.mako
Labels: 7.0

#257 Syncing from upstream OCA/l10n-switzerland (11.0)
  l10n_ch_account_tags/static/description/index.html
  l10n_ch_mis_reports/static/description/index.html
Labels: 11.0

#258 Syncing from upstream OCA/l10n-switzerland (12.0)
  l10n_ch_account_tags/static/description/index.html
  l10n_ch_base_bank/static/description/index.html
  l10n_ch_mis_reports/static/description/index.html
  l10n_ch_pain_base/static/description/index.html
  l10n_ch_pain_credit_transfer/static/description/index.html
  l10n_ch_payment_slip/static/description/index.html
  l10n_ch_states/static/description/index.html
  l10n_ch_zip/static/description/index.html
Labels: 12.0
