Repository brain-tec/l10n-switzerland, pull requests merged in 2022-07, with the labels that each got.

#396 [bt#19455] QR-Bill installation, cancel invoice
  l10n_ch_base_bank/__manifest__.py
  l10n_ch_base_bank/models/bank.py
  l10n_ch_base_bank/models/invoice.py
  l10n_ch_base_bank/tests/test_search_invoice.py
Labels: 11.0.project_el_543

#397 Syncing from upstream OCA/l10n-switzerland (13.0)
  .github/workflows/pre-commit.yml
  README.md
  ebill_paynet/__manifest__.py
  ebill_paynet/messages/invoice-2003A.xml
  ebill_paynet/messages/invoice-2013A.xml
  ebill_paynet/models/account_invoice.py
  ebill_paynet/tests/examples/invoice_qr_b2b_rounded.xml
  ebill_paynet/tests/test_invoice_message_b2b.py
Labels: 13.0

#399 Syncing from upstream OCA/l10n-switzerland (14.0)
  README.md
  ebill_paynet/__manifest__.py
  ebill_paynet/messages/invoice-2003A.jinja
  ebill_paynet/messages/invoice-2013A.jinja
  ebill_paynet/models/account_invoice.py
  ebill_paynet/tests/examples/invoice_qr_b2b_rounded.xml
  ebill_paynet/tests/test_invoice_message_b2b.py
Labels: 14.0
