Repository brain-tec/l10n-switzerland, pull requests merged in 2024-06, with the labels that each got.

#509 Syncing from upstream OCA/l10n-switzerland (14.0)
  README.md
  l10n_ch_adr_report/README.rst
  l10n_ch_adr_report/__init__.py
  l10n_ch_adr_report/__manifest__.py
  l10n_ch_adr_report/i18n/de.po
  l10n_ch_adr_report/i18n/fr.pot
  l10n_ch_adr_report/i18n/l10n_ch_adr_report.pot
  l10n_ch_adr_report/models/__init__.py
  l10n_ch_adr_report/models/product_product.py
  l10n_ch_adr_report/readme/AUTHORS.rst
  l10n_ch_adr_report/readme/CONTRIBUTORS.rst
  l10n_ch_adr_report/readme/CREDITS.rst
  l10n_ch_adr_report/readme/DESCRIPTION.rst
  l10n_ch_adr_report/report/DG_ch_delivery_report.xml
  l10n_ch_adr_report/report/__init__.py
  l10n_ch_adr_report/report/dangerous_delivery_report.py
  l10n_ch_adr_report/static/description/icon.png
  l10n_ch_adr_report/static/description/index.html
  l10n_ch_adr_report/static/src/scss/adr_report.scss
  l10n_ch_adr_report/views/assets.xml
  oca_dependencies.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/l10n_ch_adr_report/odoo/addons/l10n_ch_adr_report
  setup/l10n_ch_adr_report/setup.py
Labels: 14.0

#510 Syncing from upstream OCA/l10n-switzerland (14.0)
  .copier-answers.yml
  .github/workflows/test.yml
  .travis.yml
  README.md
  l10n_ch_adr_report/i18n/de.po
  l10n_ch_adr_report/i18n/l10n_ch_adr_report.pot
Labels: 14.0

#511 16.0 mig l10n ch base bank
  l10n_ch_base_bank/README.rst
  l10n_ch_base_bank/__init__.py
  l10n_ch_base_bank/__manifest__.py
  l10n_ch_base_bank/i18n/de.po
  l10n_ch_base_bank/i18n/fr.po
  l10n_ch_base_bank/i18n/it.po
  l10n_ch_base_bank/i18n/l10n_ch_base_bank.pot
  l10n_ch_base_bank/models/__init__.py
  l10n_ch_base_bank/models/bank.py
  l10n_ch_base_bank/models/invoice.py
  l10n_ch_base_bank/models/partner_bank.py
  l10n_ch_base_bank/postfinance.py
  l10n_ch_base_bank/readme/CONTRIBUTORS.rst
  l10n_ch_base_bank/readme/CREDITS.rst
  l10n_ch_base_bank/readme/DESCRIPTION.rst
  l10n_ch_base_bank/readme/USAGE.rst
  l10n_ch_base_bank/static/description/icon.png
  l10n_ch_base_bank/static/description/index.html
  l10n_ch_base_bank/tests/__init__.py
  l10n_ch_base_bank/tests/test_bank.py
  l10n_ch_base_bank/tests/test_bank_type.py
  l10n_ch_base_bank/tests/test_create_invoice.py
  l10n_ch_base_bank/tests/test_search_invoice.py
  l10n_ch_base_bank/views/bank.xml
  setup/l10n_ch_base_bank/odoo/addons/l10n_ch_base_bank
  setup/l10n_ch_base_bank/setup.py
Labels: 16.0, 16.0.project_gr_233

#514 16.0 mig l10n ch pain base
  l10n_ch_pain_base/README.rst
  l10n_ch_pain_base/__init__.py
  l10n_ch_pain_base/__manifest__.py
  l10n_ch_pain_base/i18n/de.po
  l10n_ch_pain_base/i18n/fr.po
  l10n_ch_pain_base/i18n/it.po
  l10n_ch_pain_base/i18n/l10n_ch_pain_base.pot
  l10n_ch_pain_base/models/__init__.py
  l10n_ch_pain_base/models/account_move_line.py
  l10n_ch_pain_base/models/account_payment_line.py
  l10n_ch_pain_base/models/account_payment_order.py
  l10n_ch_pain_base/readme/CONTRIBUTORS.rst
  l10n_ch_pain_base/readme/DESCRIPTION.rst
  l10n_ch_pain_base/static/description/icon.png
  l10n_ch_pain_base/static/description/index.html
  l10n_ch_pain_base/views/account_payment_line.xml
  setup/l10n_ch_pain_base/odoo/addons/l10n_ch_pain_base
  setup/l10n_ch_pain_base/setup.py
Labels: 16.0.project_gr_233

#513 16.0 mig l10n ch pain credit transfer
  l10n_ch_pain_credit_transfer/README.rst
  l10n_ch_pain_credit_transfer/__init__.py
  l10n_ch_pain_credit_transfer/__manifest__.py
  l10n_ch_pain_credit_transfer/data/pain.001.001.03.ch.02.xsd
  l10n_ch_pain_credit_transfer/i18n/de.po
  l10n_ch_pain_credit_transfer/i18n/fr.po
  l10n_ch_pain_credit_transfer/i18n/l10n_ch_pain_credit_transfer.pot
  l10n_ch_pain_credit_transfer/models/__init__.py
  l10n_ch_pain_credit_transfer/models/account_payment_method.py
  l10n_ch_pain_credit_transfer/readme/CONFIGURE.rst
  l10n_ch_pain_credit_transfer/readme/CONTRIBUTORS.rst
  l10n_ch_pain_credit_transfer/readme/DESCRIPTION.rst
  l10n_ch_pain_credit_transfer/readme/USAGE.rst
  l10n_ch_pain_credit_transfer/static/description/icon.png
  l10n_ch_pain_credit_transfer/static/description/index.html
  l10n_ch_pain_credit_transfer/tests/__init__.py
  l10n_ch_pain_credit_transfer/tests/test_ch_sct.py
  setup/l10n_ch_pain_credit_transfer/odoo/addons/l10n_ch_pain_credit_transfer
  setup/l10n_ch_pain_credit_transfer/setup.py
Labels: 16.0.project_gr_233

#517 16.0 mig l10n ch pain base
  l10n_ch_pain_base/README.rst
  l10n_ch_pain_base/__init__.py
  l10n_ch_pain_base/__manifest__.py
  l10n_ch_pain_base/i18n/de.po
  l10n_ch_pain_base/i18n/fr.po
  l10n_ch_pain_base/i18n/it.po
  l10n_ch_pain_base/i18n/l10n_ch_pain_base.pot
  l10n_ch_pain_base/models/__init__.py
  l10n_ch_pain_base/models/account_move_line.py
  l10n_ch_pain_base/models/account_payment_line.py
  l10n_ch_pain_base/models/account_payment_order.py
  l10n_ch_pain_base/readme/CONTRIBUTORS.rst
  l10n_ch_pain_base/readme/DESCRIPTION.rst
  l10n_ch_pain_base/static/description/icon.png
  l10n_ch_pain_base/static/description/index.html
  l10n_ch_pain_base/views/account_payment_line.xml
  setup/l10n_ch_pain_base/odoo/addons/l10n_ch_pain_base
  setup/l10n_ch_pain_base/setup.py
Labels: 16.0.project_gr_233

#516 16.0 mig l10n ch pain credit transfer
  l10n_ch_pain_credit_transfer/README.rst
  l10n_ch_pain_credit_transfer/__init__.py
  l10n_ch_pain_credit_transfer/__manifest__.py
  l10n_ch_pain_credit_transfer/data/pain.001.001.03.ch.02.xsd
  l10n_ch_pain_credit_transfer/i18n/de.po
  l10n_ch_pain_credit_transfer/i18n/fr.po
  l10n_ch_pain_credit_transfer/i18n/l10n_ch_pain_credit_transfer.pot
  l10n_ch_pain_credit_transfer/models/__init__.py
  l10n_ch_pain_credit_transfer/models/account_payment_method.py
  l10n_ch_pain_credit_transfer/readme/CONFIGURE.rst
  l10n_ch_pain_credit_transfer/readme/CONTRIBUTORS.rst
  l10n_ch_pain_credit_transfer/readme/DESCRIPTION.rst
  l10n_ch_pain_credit_transfer/readme/USAGE.rst
  l10n_ch_pain_credit_transfer/static/description/icon.png
  l10n_ch_pain_credit_transfer/static/description/index.html
  l10n_ch_pain_credit_transfer/tests/__init__.py
  l10n_ch_pain_credit_transfer/tests/test_ch_sct.py
  setup/l10n_ch_pain_credit_transfer/odoo/addons/l10n_ch_pain_credit_transfer
  setup/l10n_ch_pain_credit_transfer/setup.py
Labels: 16.0.project_gr_233

#520 Syncing from upstream OCA/l10n-switzerland (11.0)
  l10n_ch_account_tags/README.rst
  l10n_ch_account_tags/__manifest__.py
  l10n_ch_account_tags/static/description/index.html
Labels: 11.0

#521 Syncing from upstream OCA/l10n-switzerland (12.0)
  l10n_ch_account_tags/README.rst
  l10n_ch_account_tags/__manifest__.py
  l10n_ch_account_tags/static/description/index.html
  l10n_ch_fix_isr_reference/__manifest__.py
Labels: 12.0

#522 Syncing from upstream OCA/l10n-switzerland (13.0)
  ebill_paynet/README.rst
  ebill_paynet/__manifest__.py
  ebill_paynet/static/description/index.html
  ebill_paynet_customer_free_ref/README.rst
  ebill_paynet_customer_free_ref/__manifest__.py
  ebill_paynet_customer_free_ref/static/description/index.html
  l10n_ch_account_tags/README.rst
  l10n_ch_account_tags/__manifest__.py
  l10n_ch_account_tags/static/description/index.html
Labels: 13.0

#523 Syncing from upstream OCA/l10n-switzerland (14.0)
  ebill_paynet/README.rst
  ebill_paynet/__manifest__.py
  ebill_paynet/static/description/index.html
  ebill_paynet_customer_free_ref/README.rst
  ebill_paynet_customer_free_ref/__manifest__.py
  ebill_paynet_customer_free_ref/static/description/index.html
  l10n_ch_account_tags/__manifest__.py
Labels: 14.0

#524 Syncing from upstream OCA/l10n-switzerland (16.0)
  l10n_ch_account_tags/__manifest__.py
Labels: 16.0

#525 Syncing from upstream OCA/l10n-switzerland (17.0)
  README.md
  l10n_ch_qr_no_amount/README.rst
  l10n_ch_qr_no_amount/__init__.py
  l10n_ch_qr_no_amount/__manifest__.py
  l10n_ch_qr_no_amount/i18n/l10n_ch_qr_no_amount.pot
  l10n_ch_qr_no_amount/models/__init__.py
  l10n_ch_qr_no_amount/models/res_partner_bank.py
  l10n_ch_qr_no_amount/pyproject.toml
  l10n_ch_qr_no_amount/readme/CONTRIBUTORS.md
  l10n_ch_qr_no_amount/readme/CREDITS.md
  l10n_ch_qr_no_amount/readme/DESCRIPTION.md
  l10n_ch_qr_no_amount/readme/USAGE.md
  l10n_ch_qr_no_amount/report/__init__.py
  l10n_ch_qr_no_amount/report/swissqr_no_amount_report.py
  l10n_ch_qr_no_amount/report/swissqr_no_amount_report.xml
  l10n_ch_qr_no_amount/static/description/icon.png
  l10n_ch_qr_no_amount/static/description/index.html
  l10n_ch_qr_no_amount/static/src/img/Betragsfeld_Eckmarke.png
  l10n_ch_qr_no_amount/static/src/img/Feld_Betrag_40x15mm.png
  l10n_ch_qr_no_amount/static/src/scss/report_swissqr_no_amount.scss
  setup/_metapackage/pyproject.toml
Labels: 17.0
